epoint:
  baseUrl: https://epoint.az/api/1
  resultUrl: https://api.fitnest.az/payment/callback
hpa:
  cpuUtilization: '90'
  enabled: false
  maxReplicas: '3'
  memoryUtilization: 450Mi
  minReplicas: '1'
image:
  imagePullSecrets:
    - name: ghcr-secret
  pullPolicy: IfNotPresent
  repository: ghcr.io/fitnest-code/payment-backend
  tag: production-d1cdf7e
networkPolicy:
  allowedServices:
    - user-backend
    - identity-backend
    - order-backend
  enabled: true
replicaCount: 1
resources:
  requests:
    cpu: 200m
    memory: 1024Mi
  limits:
    cpu: 1500m
    memory: 1536Mi
service:
  grpcPort: 9090
  port: 8080
  type: ClusterIP
vaultEnv: production
database:
  hikariMaxPool: 30
  hikariMinIdle: 10
